# Generated by Django 5.1.1 on 2024-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Todo Title'),
        ),
    ]
