# Generated by Django 5.1.1 on 2024-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_contact_phone_number_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='deptname',
            new_name='dep_name',
        ),
    ]
